services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: fer-api
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: fer-client
    ports:
      - "3000:3000"
